bmFtZTogRGVwbG95CgpvbjoKICB3b3JrZmxvd19jYWxsOgogICAgaW5wdXRz
OgogICAgICBlbnZpcm9ubWVudDoKICAgICAgICByZXF1aXJlZDogdHJ1ZQog
ICAgICAgIHR5cGU6IHN0cmluZwogICAgc2VjcmV0czoKICAgICAgUzNfQlVD
S0VUX05BTUU6CiAgICAgICAgcmVxdWlyZWQ6IHRydWUKICAgICAgTlBNUkM6
CiAgICAgICAgcmVxdWlyZWQ6IHRydWUKICAgICAgTkVYVF9QVUJMSUNfUFJJ
U01JQ19SRVBPOgogICAgICAgIHJlcXVpcmVkOiB0cnVlCgpqb2JzOgogIGRl
cGxveToKICAgIG5hbWU6IERlcGxveQogICAgZW52aXJvbm1lbnQ6ICR7eyBp
bnB1dHMuZW52aXJvbm1lbnQgfX0KICAgIHJ1bnMtb246CiAgICAgIC0gc2Vs
Zi1ob3N0ZWQKICAgICAgLSBsaW51eAogICAgY29udGFpbmVyOgogICAgICBp
bWFnZTogZGV2LWNsZWFyLXJlZ2lzdHJ5LmNsZWFybWUuY29tL2NsZWFyL25v
ZGUtMTQ6MjAyMi4wMS4wNQogICAgICBvcHRpb25zOiAtLXVzZXIgcm9vdAog
ICAgZW52OgogICAgICBTM19CVUNLRVRfTkFNRTogJHt7IHNlY3JldHMuUzNf
QlVDS0VUX05BTUUgfX0KICAgICAgTlBNUkM6ICR7eyBzZWNyZXRzLk5QTVJD
IH19CiAgICAgIE5FWFRfUFVCTElDX1BSSVNNSUNfUkVQTzogJHt7IHNlY3Jl
dHMuTkVYVF9QVUJMSUNfUFJJU01JQ19SRVBPIH19CiAgICBzdGVwczoKICAg
ICAgLSBuYW1lOiBDcmVhdGluZyB+Ly5ucG1yYwogICAgICAgIHJ1bjogZWNo
byAkTlBNUkMgfCBiYXNlNjQgLWQgPiB+Ly5ucG1yYwoKICAgICAgLSB1c2Vz
OiBhY3Rpb25zL2NoZWNrb3V0QHYyCgogICAgICAtIG5hbWU6IEluc3RhbGwg
Tm9kZSBNb2R1bGVzCiAgICAgICAgcnVuOiB5YXJuCgogICAgICAtIG5hbWU6
IEJ1aWxkCiAgICAgICAgcnVuOiB5YXJuIGJ1aWxkCgogICAgICAtIG5hbWU6
IENvbmZpZ3VyZSBBV1MgY3JlZGVudGlhbHMKICAgICAgICB1c2VzOiBhd3Mt
YWN0aW9ucy9jb25maWd1cmUtYXdzLWNyZWRlbnRpYWxzQHYxCiAgICAgICAg
d2l0aDoKICAgICAgICAgIHJvbGUtdG8tYXNzdW1lOiBhcm46YXdzOmlhbTo6
OTgyNDY0NTIwNjAyOnJvbGUvdGVycmFncnVudF9wb3dlcl9yb2xlCiAgICAg
ICAgICBhd3MtcmVnaW9uOiB1cy1lYXN0LTEKICAgICAgICAgIHJvbGUtZHVy
YXRpb24tc2Vjb25kczogOTAwCgogICAgICAtIG5hbWU6IEluc3RhbGwgQVdT
IGRlcGVuZGVuY2llcwogICAgICAgIHJ1bjogfAogICAgICAgICAgY3VybCAi
aHR0cHM6Ly9hd3NjbGkuYW1hem9uYXdzLmNvbS9hd3NjbGktZXhlLWxpbnV4
LXg4Nl82NC56aXAiIC1vICJhd3NjbGl2Mi56aXAiCiAgICAgICAgICBybSAt
cmYgLi9hd3MgfHwgdHJ1ZQogICAgICAgICAgdW56aXAgLW8gLXEgYXdzY2xp
djIuemlwIHx8IHRydWUKICAgICAgICAgIC4vYXdzL2luc3RhbGwgLXUKCiAg
ICAgIC0gbmFtZTogUmVtb3ZlIC5odG1sIGV4dGVuc2lvbnMKICAgICAgICBy
dW46IGJhc2ggLi9zY3JpcHRzL3JlbW92ZS1odG1sLWV4dGVuc2lvbi5zaAoK
ICAgICAgLSBuYW1lOiBVcGxvYWQgdG8gczMKICAgICAgICBydW46IHwKICAg
ICAgICAgIGF3cyBzMyBzeW5jIG91dCBzMzovLyRTM19CVUNLRVRfTkFNRSAt
LWV4Y2x1ZGUgIiouanMiIC0tZXhjbHVkZSAiKi5qc29uIiAtLWV4Y2x1ZGUg
IioubWFwIiAtLWV4Y2x1ZGUgIiouY3NzIiAtLWNvbnRlbnQtdHlwZSAidGV4
dC9odG1sIgogICAgICAgICAgYXdzIHMzIHN5bmMgb3V0IHMzOi8vJFMzX0JV
Q0tFVF9OQU1FIC0tZGVsZXRlCg==
